# Generated by Django 5.2.15 on 2026-06-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='event_date',
            field=models.DateTimeField(verbose_name='活动时间'),
        ),
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='场地号'),
        ),
    ]
