# Generated by Django 5.2.15 on 2026-07-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotation', '0004_session_event_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='session',
            name='rounds',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='轮次数'),
        ),
    ]
